/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import static app.VentanaPrincipal.content;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Leider
 */
public class Admin extends javax.swing.JPanel {
    
    Color letra=new Color(0,15,29);
    Color fueraJ=new Color(0,0,87);
    Color naranjado=new Color(255,180,80);
    
    String Usuario = "cablebojaya";
    String Contraseña = "bojaya2022";
    String Us;
    String Con;
    
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        Inicio = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jTextUsu = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        subBarra = new javax.swing.JPanel();
        logi = new javax.swing.JLabel();
        jTextEntrar = new javax.swing.JPanel();
        jEntrar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 660));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));

        Inicio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Inicio.setForeground(new java.awt.Color(0, 15, 29));
        Inicio.setText("Admin");

        Contenido.setBackground(new java.awt.Color(0, 15, 29));

        login.setBackground(new java.awt.Color(0, 15, 29));
        login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 51)));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        jTextUsu.setBackground(new java.awt.Color(0, 15, 29));
        jTextUsu.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jTextUsu.setForeground(new java.awt.Color(255, 255, 255));
        jTextUsu.setText("Usuario");
        jTextUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextUsuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextUsuMouseExited(evt);
            }
        });

        jPassword.setBackground(new java.awt.Color(0, 15, 29));
        jPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.setText("jPasswordField1");
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordMouseExited(evt);
            }
        });

        subBarra.setBackground(new java.awt.Color(0, 0, 0));

        logi.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        logi.setForeground(new java.awt.Color(255, 255, 255));
        logi.setText("Iniciar Sesión");

        javax.swing.GroupLayout subBarraLayout = new javax.swing.GroupLayout(subBarra);
        subBarra.setLayout(subBarraLayout);
        subBarraLayout.setHorizontalGroup(
            subBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subBarraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logi)
                .addGap(122, 122, 122))
        );
        subBarraLayout.setVerticalGroup(
            subBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subBarraLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(logi))
        );

        jTextEntrar.setBackground(new java.awt.Color(0, 15, 29));
        jTextEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextEntrarMouseExited(evt);
            }
        });

        jEntrar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEntrar.setText("Entrar");
        jEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 15, 29)));

        javax.swing.GroupLayout jTextEntrarLayout = new javax.swing.GroupLayout(jTextEntrar);
        jTextEntrar.setLayout(jTextEntrarLayout);
        jTextEntrarLayout.setHorizontalGroup(
            jTextEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        jTextEntrarLayout.setVerticalGroup(
            jTextEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jTextEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addComponent(subBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jTextUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jTextEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Inicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        logi.setForeground(letra);
        subBarra.setBackground(Color.WHITE);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        logi.setForeground(Color.white);
        subBarra.setBackground(Color.BLACK);
    }//GEN-LAST:event_loginMouseExited

    private void jTextUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUsuMouseEntered
        logi.setForeground(Color.BLACK);
        subBarra.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextUsuMouseEntered

    private void jPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseEntered
        logi.setForeground(Color.BLACK);
        subBarra.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPasswordMouseEntered

    private void jTextUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUsuMouseExited
        logi.setForeground(letra);
    }//GEN-LAST:event_jTextUsuMouseExited

    private void jPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseExited
        logi.setForeground(letra);
    }//GEN-LAST:event_jPasswordMouseExited

    private void jTextUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUsuMouseClicked
        jTextUsu.setText(null);
    }//GEN-LAST:event_jTextUsuMouseClicked

    private void jPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseClicked
        jPassword.setText(null);
    }//GEN-LAST:event_jPasswordMouseClicked

    private void jTextEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextEntrarMouseEntered
        jEntrar.setForeground(Color.white);
        jTextEntrar.setBackground(naranjado);
        subBarra.setBackground(Color.WHITE);
        subBarra.setForeground(Color.white);
    }//GEN-LAST:event_jTextEntrarMouseEntered

    private void jTextEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextEntrarMouseExited
        jEntrar.setForeground(Color.WHITE);
        jTextEntrar.setBackground(letra);
    }//GEN-LAST:event_jTextEntrarMouseExited

    private void jTextEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextEntrarMouseClicked
        Us = jTextUsu.getText();
        Con= jPassword.getText();
        System.out.println(Us);
        System.out.println(Con);
        
        if ((Us.equals(Usuario)) && (Con.equals(Contraseña))) {
            System.out.println("correcto");
            Informe in = new Informe();
            in.setSize(870, 710);
            in.setLocation(0,0);

            content.removeAll();
            content.add(in, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            
        } else if(!Us.equals(Usuario) || !Con.equals(Contraseña)) {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta");
        }
    }//GEN-LAST:event_jTextEntrarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Inicio;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel jEntrar;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPanel jTextEntrar;
    private javax.swing.JTextField jTextUsu;
    private javax.swing.JLabel logi;
    private javax.swing.JPanel login;
    private javax.swing.JPanel subBarra;
    // End of variables declaration//GEN-END:variables


}
