/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import com.itextpdf.io.font.FontProgram;
import com.itextpdf.io.font.FontProgramFactory;
import com.itextpdf.io.font.PdfEncodings;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.VerticalAlignment;
import conexion.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leider
 */
public class Facturas extends javax.swing.JPanel {

    Color naranja = new Color(0,15,29);
    Color naranjado = new Color(255, 180, 80);
    Conexion con = new Conexion();
    Connection cn;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel modelo;
    int id;
    
    
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    int dia = now.getDayOfMonth();
    int month = now.getMonthValue();
    String fecha = dia+ " de " + month +" de "+year;
    

    public Facturas() {
        initComponents();
        generarPng.setIcon(new javax.swing.ImageIcon("./img/generarb.png"));
        visualizarPng.setIcon(new javax.swing.ImageIcon("./img/mostrarb.png"));
        imprimirPng.setIcon(new javax.swing.ImageIcon("./img/imprimirb.png"));
        imprimirPng1.setIcon(new javax.swing.ImageIcon("./img/imprimirb.png"));
        buscarPng.setIcon(new javax.swing.ImageIcon("./img/buscarb.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Contenido = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        GenerarBtn = new javax.swing.JPanel();
        GenerarTxt = new javax.swing.JLabel();
        generarPng = new javax.swing.JLabel();
        VisualizarBtn = new javax.swing.JPanel();
        VisualizarTxt = new javax.swing.JLabel();
        visualizarPng = new javax.swing.JLabel();
        ImpimirGBtn = new javax.swing.JPanel();
        ImprimirGTxt = new javax.swing.JLabel();
        imprimirPng = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        clienteTxt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        BuscarBtn = new javax.swing.JPanel();
        BuscarTxt = new javax.swing.JLabel();
        buscarPng = new javax.swing.JLabel();
        ImprimirBtn = new javax.swing.JPanel();
        ImprimirTxt = new javax.swing.JLabel();
        imprimirPng1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Contenido.setBackground(new java.awt.Color(0, 15, 29));
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 15, 29));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 2, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GenerarBtn.setBackground(new java.awt.Color(0, 15, 29));
        GenerarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GenerarBtn.setPreferredSize(new java.awt.Dimension(242, 56));
        GenerarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GenerarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GenerarBtnMouseExited(evt);
            }
        });

        GenerarTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        GenerarTxt.setForeground(new java.awt.Color(255, 255, 255));
        GenerarTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GenerarTxt.setText("Generar");

        generarPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout GenerarBtnLayout = new javax.swing.GroupLayout(GenerarBtn);
        GenerarBtn.setLayout(GenerarBtnLayout);
        GenerarBtnLayout.setHorizontalGroup(
            GenerarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GenerarBtnLayout.createSequentialGroup()
                .addComponent(generarPng, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenerarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        GenerarBtnLayout.setVerticalGroup(
            GenerarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenerarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GenerarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generarPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GenerarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(GenerarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 50));

        VisualizarBtn.setBackground(new java.awt.Color(0, 15, 29));
        VisualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisualizarBtn.setPreferredSize(new java.awt.Dimension(242, 56));
        VisualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisualizarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisualizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisualizarBtnMouseExited(evt);
            }
        });

        VisualizarTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        VisualizarTxt.setForeground(new java.awt.Color(255, 255, 255));
        VisualizarTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VisualizarTxt.setText("Visualizar");

        visualizarPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout VisualizarBtnLayout = new javax.swing.GroupLayout(VisualizarBtn);
        VisualizarBtn.setLayout(VisualizarBtnLayout);
        VisualizarBtnLayout.setHorizontalGroup(
            VisualizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VisualizarBtnLayout.createSequentialGroup()
                .addComponent(visualizarPng, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisualizarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        VisualizarBtnLayout.setVerticalGroup(
            VisualizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VisualizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualizarPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisualizarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(VisualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 50));

        ImpimirGBtn.setBackground(new java.awt.Color(0, 15, 29));
        ImpimirGBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImpimirGBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImpimirGBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImpimirGBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImpimirGBtnMouseExited(evt);
            }
        });

        ImprimirGTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ImprimirGTxt.setForeground(new java.awt.Color(255, 255, 255));
        ImprimirGTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ImprimirGTxt.setText("Imprimir");

        imprimirPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ImpimirGBtnLayout = new javax.swing.GroupLayout(ImpimirGBtn);
        ImpimirGBtn.setLayout(ImpimirGBtnLayout);
        ImpimirGBtnLayout.setHorizontalGroup(
            ImpimirGBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImpimirGBtnLayout.createSequentialGroup()
                .addComponent(imprimirPng, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImprimirGTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        ImpimirGBtnLayout.setVerticalGroup(
            ImpimirGBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImpimirGBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ImpimirGBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imprimirPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImprimirGTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(ImpimirGBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 50));

        Contenido.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 260, 180));

        jPanel6.setBackground(new java.awt.Color(0, 15, 29));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 2, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de factura", "Id del cliente", "Fecha de factura", "Valor", "Estado", "Fecha de pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFacturas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        Contenido.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 310));

        jPanel3.setBackground(new java.awt.Color(0, 15, 29));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Individual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 2, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(270, 180));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id del cliente:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        clienteTxt.setBackground(new java.awt.Color(0, 15, 29));
        clienteTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        clienteTxt.setForeground(new java.awt.Color(255, 255, 255));
        clienteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtActionPerformed(evt);
            }
        });
        jPanel3.add(clienteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 35, 20));

        jPanel10.setBackground(new java.awt.Color(0, 15, 29));

        BuscarBtn.setBackground(new java.awt.Color(0, 15, 29));
        BuscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarBtnMouseExited(evt);
            }
        });

        BuscarTxt.setBackground(new java.awt.Color(0, 15, 29));
        BuscarTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BuscarTxt.setForeground(new java.awt.Color(255, 255, 255));
        BuscarTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BuscarTxt.setText("Buscar");

        buscarPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout BuscarBtnLayout = new javax.swing.GroupLayout(BuscarBtn);
        BuscarBtn.setLayout(BuscarBtnLayout);
        BuscarBtnLayout.setHorizontalGroup(
            BuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarBtnLayout.createSequentialGroup()
                .addComponent(buscarPng, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        BuscarBtnLayout.setVerticalGroup(
            BuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        ImprimirBtn.setBackground(new java.awt.Color(0, 15, 29));
        ImprimirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImprimirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImprimirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImprimirBtnMouseExited(evt);
            }
        });

        ImprimirTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ImprimirTxt.setForeground(new java.awt.Color(255, 255, 255));
        ImprimirTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ImprimirTxt.setText("Imprimir");

        imprimirPng1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ImprimirBtnLayout = new javax.swing.GroupLayout(ImprimirBtn);
        ImprimirBtn.setLayout(ImprimirBtnLayout);
        ImprimirBtnLayout.setHorizontalGroup(
            ImprimirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImprimirBtnLayout.createSequentialGroup()
                .addComponent(imprimirPng1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImprimirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ImprimirBtnLayout.setVerticalGroup(
            ImprimirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImprimirBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ImprimirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imprimirPng1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImprimirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImprimirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ImprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        Contenido.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 260, 180));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 15, 29));
        jLabel10.setText("Facturas");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clienteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtActionPerformed

    private void GenerarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarBtnMouseEntered
        GenerarBtn.setBackground(naranjado);
        GenerarTxt.setForeground(Color.black);
        generarPng.setIcon(new javax.swing.ImageIcon("./img/generar.png"));
    }//GEN-LAST:event_GenerarBtnMouseEntered

    private void GenerarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarBtnMouseExited
        GenerarBtn.setBackground(naranja);
        GenerarTxt.setForeground(Color.white);
        generarPng.setIcon(new javax.swing.ImageIcon("./img/generarb.png"));
    }//GEN-LAST:event_GenerarBtnMouseExited

    private void VisualizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizarBtnMouseEntered
        VisualizarBtn.setBackground(naranjado);
        VisualizarTxt.setForeground(Color.black);
        visualizarPng.setIcon(new javax.swing.ImageIcon("./img/mostrar.png"));
    }//GEN-LAST:event_VisualizarBtnMouseEntered

    private void VisualizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizarBtnMouseExited
        VisualizarBtn.setBackground(naranja);
        VisualizarTxt.setForeground(Color.white);
        visualizarPng.setIcon(new javax.swing.ImageIcon("./img/mostrarb.png"));
    }//GEN-LAST:event_VisualizarBtnMouseExited

    private void ImpimirGBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImpimirGBtnMouseEntered
        ImpimirGBtn.setBackground(naranjado);
        ImprimirGTxt.setForeground(Color.black);
        imprimirPng.setIcon(new javax.swing.ImageIcon("./img/imprimir.png"));
    }//GEN-LAST:event_ImpimirGBtnMouseEntered

    private void ImpimirGBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImpimirGBtnMouseExited
        ImpimirGBtn.setBackground(naranja);
        ImprimirGTxt.setForeground(Color.white);
        imprimirPng.setIcon(new javax.swing.ImageIcon("./img/imprimirb.png"));
    }//GEN-LAST:event_ImpimirGBtnMouseExited

    private void BuscarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtnMouseEntered
        BuscarBtn.setBackground(naranjado);
        BuscarTxt.setForeground(Color.black);
        buscarPng.setIcon(new javax.swing.ImageIcon("./img/buscar.png"));
    }//GEN-LAST:event_BuscarBtnMouseEntered

    private void BuscarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtnMouseExited
        BuscarBtn.setBackground(naranja);
        BuscarTxt.setForeground(Color.white);
        buscarPng.setIcon(new javax.swing.ImageIcon("./img/buscarb.png"));
    }//GEN-LAST:event_BuscarBtnMouseExited

    private void ImprimirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirBtnMouseEntered
        ImprimirBtn.setBackground(naranjado);
        ImprimirTxt.setForeground(Color.black);
        imprimirPng1.setIcon(new javax.swing.ImageIcon("./img/imprimir.png"));
    }//GEN-LAST:event_ImprimirBtnMouseEntered

    private void ImprimirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirBtnMouseExited
        ImprimirBtn.setBackground(naranja);
        ImprimirTxt.setForeground(Color.white);
        imprimirPng1.setIcon(new javax.swing.ImageIcon("./img/imprimirb.png"));
    }//GEN-LAST:event_ImprimirBtnMouseExited

    private void GenerarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarBtnMouseClicked
        generarFacturas();
        visualizarFacturas();
    }//GEN-LAST:event_GenerarBtnMouseClicked

    private void BuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtnMouseClicked
        buscarIndividual();
    }//GEN-LAST:event_BuscarBtnMouseClicked

    private void ImpimirGBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImpimirGBtnMouseClicked
        try {
            new Facturas().manipulatePdf();
            JOptionPane.showMessageDialog(null, "documentos Generados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ImpimirGBtnMouseClicked

    private void VisualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizarBtnMouseClicked
        visualizarFacturas();
    }//GEN-LAST:event_VisualizarBtnMouseClicked

    private void generarFacturas() {

        String sql = "insert into factura(id_cliente) select distinct(id_cliente) from t_cliente";
        try {
            cn = con.getConnection();
            st = cn.createStatement();
            st.executeUpdate(sql);
            modelo = (DefaultTableModel) tblFacturas.getModel();
            tblFacturas.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Facturas generadas exitosamente");
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void visualizarFacturas() {

        String sql = "select * from factura";
        try {
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] cliente = new Object[6];
            modelo = (DefaultTableModel) tblFacturas.getModel();
            while (rs.next()) {
                cliente[0] = rs.getInt("num_factura");
                cliente[1] = rs.getInt("id_cliente");
                cliente[2] = rs.getDate("fecha_fact");
                cliente[3] = rs.getInt("valor");
                cliente[4] = rs.getString("estado");
                cliente[5] = rs.getDate("fecha_pag");
                modelo.addRow(cliente);
            }
            tblFacturas.setModel(modelo);
            modelo = (DefaultTableModel) tblFacturas.getModel();
            tblFacturas.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void buscarIndividual() {

        String id = clienteTxt.getText();
        String sql = "select * from factura group by  id_cliente='" + id + "'";
        try {
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] cliente = new Object[6];
            modelo = (DefaultTableModel) tblFacturas.getModel();
            while (rs.next()) {
                cliente[0] = rs.getInt("num_factura");
                cliente[1] = rs.getInt("id_cliente");
                cliente[2] = rs.getDate("fecha_fact");
                cliente[3] = rs.getInt("valor");
                cliente[4] = rs.getString("estado");
                cliente[5] = rs.getDate("fecha_pag");
                modelo.addRow(cliente);
            }
            tblFacturas.setModel(modelo);
            modelo = (DefaultTableModel) tblFacturas.getModel();
            tblFacturas.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void manipulatePdf() throws Exception {

        String sql = "SELECT t_cliente.nom_cliente, \n" +
        "t_cliente.dir_cliente, \n" +
        "t_cliente.ced_cliente, \n" +
        "t_cliente.id_cliente, \n" +
        "factura.num_factura,\n" +
        "factura.valor, \n" +
        "factura.fecha_fact, \n" +
        "SUM(factura.valor)-(20000) AS deuda_total,\n" +
        "factura.estado\n" +
        "FROM t_cliente \n" +
        "INNER JOIN factura  \n" +
        "ON t_cliente.id_cliente = factura.id_cliente\n" +
        "WHERE factura.estado = 'pendiente' GROUP BY factura.id_cliente;";
        
        try {
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] cliente = new Object[8];

            String rutaFuente = "./fuentes/orange juice 2.0.ttf";
            FontProgram fu = FontProgramFactory.createFont(rutaFuente);
            PdfFont fue = PdfFontFactory.createFont(fu, PdfEncodings.WINANSI, true);
            String imageFile = "./img/antena.png";
            ImageData data = ImageDataFactory.create(imageFile);
            Image img = new Image(data);

            String dest = "./facturas/Dia "+ fecha+".pdf";
            //File dest = new File(desti);
            PdfDocument pdfDoc = new PdfDocument(new PdfWriter(dest));
            Document doc = new Document(pdfDoc);
            pdfDoc.setDefaultPageSize(PageSize.LETTER);
            for (int i = 0; i < 4; i++) {
                float columnWidth[] = {40, 170, 280};
                Table table = new Table(columnWidth);
                table.setBackgroundColor(new DeviceRgb(40, 150, 202));
                table.setFontColor(new DeviceRgb(255, 255, 255));
                Cell cell, cell0, cell1;
                
                cell0 = new Cell().add(img.scaleAbsolute(90, 84)).setVerticalAlignment(VerticalAlignment.MIDDLE)
                        .setBorder(Border.NO_BORDER);
                table.addCell(cell0);
                cell = new Cell().add(new Paragraph("CABLE \nBOJAYÁ")
                        .setTextAlignment(TextAlignment.LEFT)
                        .setVerticalAlignment(VerticalAlignment.MIDDLE)
                        .setMarginTop(20)
                        .setMarginBottom(20f)
                        .setFontSize(20f)
                        .setFont(fue));
                table.addCell(cell.setBorder(Border.NO_BORDER));

                cell1 = new Cell().add(new Paragraph("NIT 00-000-00-0\nBojayá, Chocó\n3110007611")
                        .setTextAlignment(TextAlignment.RIGHT)
                        .setVerticalAlignment(VerticalAlignment.MIDDLE)
                        .setMarginTop(30f)
                        .setMarginBottom(30f)
                        .setMarginRight(10f));
                table.addCell(cell1.setBorder(Border.NO_BORDER));

                while (rs.next()) {

                    cliente[0] = rs.getInt("id_cliente");
                    cliente[1] = rs.getString("nom_cliente");
                    cliente[2] = rs.getString("ced_cliente");
                    cliente[3] = rs.getString("dir_cliente");
                    cliente[4] = rs.getInt("num_factura");
                    cliente[5] = rs.getDate("fecha_fact");
                    cliente[6] = rs.getInt("valor");
                    cliente[7] = rs.getInt("deuda_total");
                    System.out.println("es: " + cliente[1]);
                    System.out.println("este: " +cliente[6]+ cliente[7]);
                    int suma=0;
                    System.out.println("sumana: " +suma);
                    suma +=(int) cliente[6]+(int) cliente[7];
                    System.out.println("sumaa: " +suma);
                    String resulta = String.valueOf(suma);
                    float coluWidth[] = {80, 250, 150, 80};
                    Table infoCliente = new Table(coluWidth);

                    infoCliente.addCell(new Cell(0, 4)
                            .add(new Paragraph("Informacion del Cliente"))
                            .setBorder(Border.NO_BORDER)
                            .setBold());

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph("Nombre: "))
                            .setBorder(Border.NO_BORDER));

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph(cliente[1].toString()))
                            .setBorder(Border.NO_BORDER));

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph("No Factura: "))
                            .setBorder(Border.NO_BORDER));
                    infoCliente.addCell(new Cell()
                            .add(new Paragraph(cliente[4].toString()))
                            .setBorder(Border.NO_BORDER));

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph("No Cedula: "))
                            .setBorder(Border.NO_BORDER));
                    infoCliente.addCell(new Cell()
                            .add(new Paragraph(cliente[2].toString()))
                            .setBorder(Border.NO_BORDER));

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph("Id Cliente: "))
                            .setBorder(Border.NO_BORDER));
                    infoCliente.addCell(new Cell()
                            .add(new Paragraph(cliente[0].toString()))
                            .setBorder(Border.NO_BORDER));

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph("Direccion: "))
                            .setBorder(Border.NO_BORDER));
                    infoCliente.addCell(new Cell()
                            .add(new Paragraph(cliente[3].toString()))
                            .setBorder(Border.NO_BORDER));

                    infoCliente.addCell(new Cell()
                            .add(new Paragraph("Fecha : "))
                            .setBorder(Border.NO_BORDER));
                    infoCliente.addCell(new Cell()
                            .add(new Paragraph(cliente[5].toString()))
                            .setBorder(Border.NO_BORDER));

                    float colWidth[] = {480, 80};
                    Table infoProducto = new Table(colWidth);
                    infoProducto.setBackgroundColor(new DeviceRgb(40, 150, 202))
                            .setFontColor(new DeviceRgb(255, 255, 255))
                            .setTextAlignment(TextAlignment.CENTER);

                    infoProducto.addCell(new Cell()
                            .add(new Paragraph("Concepto"))
                            .setBorder(Border.NO_BORDER));
                    infoProducto.addCell(new Cell()
                            .add(new Paragraph("Valor"))
                            .setBorder(Border.NO_BORDER));

                    float coWidth[] = {480, 80};
                    Table infoProduct = new Table(coWidth);

                    infoProduct.addCell(new Cell()
                            .add(new Paragraph("Servicio mensual de T.V"))
                            .setTextAlignment(TextAlignment.LEFT));
                    infoProduct.addCell(new Cell()
                            .add(new Paragraph("$"+cliente[6].toString()))
                            .setTextAlignment(TextAlignment.CENTER));

                    infoProduct.addCell(new Cell()
                            .add(new Paragraph("Deuda anterior"))
                            .setTextAlignment(TextAlignment.LEFT));
                    infoProduct.addCell(new Cell()
                            .add(new Paragraph("$"+cliente[7].toString()))
                            .setTextAlignment(TextAlignment.CENTER));

                    float cWidth[] = {480, 80};
                    Table infoProduc = new Table(cWidth);
                    infoProduc.setBackgroundColor(new DeviceRgb(40, 150, 202))
                            .setFontColor(new DeviceRgb(255, 255, 255))
                            .setTextAlignment(TextAlignment.CENTER);
                    infoProduc.addCell(new Cell()
                            .add(new Paragraph("Valor total"))
                            .setTextAlignment(TextAlignment.RIGHT)
                            .setBorder(Border.NO_BORDER));
                    infoProduc.addCell(new Cell()
                            .add(new Paragraph("$"+resulta))
                            .setTextAlignment(TextAlignment.CENTER)
                            .setBorder(Border.NO_BORDER));

                    doc.add(table);
                    doc.add(new Paragraph(""));
                    doc.add(infoCliente);
                    doc.add(new Paragraph(""));
                    doc.add(infoProducto);
                    doc.add(infoProduct);
                    doc.add(new Paragraph(""));
                    doc.add(infoProduc);
                    doc.add(new Paragraph("\n"));
                                        
                    System.out.println("doc creado");

                }                
                doc.close();
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuscarBtn;
    private javax.swing.JLabel BuscarTxt;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel GenerarBtn;
    private javax.swing.JLabel GenerarTxt;
    private javax.swing.JPanel ImpimirGBtn;
    private javax.swing.JPanel ImprimirBtn;
    private javax.swing.JLabel ImprimirGTxt;
    private javax.swing.JLabel ImprimirTxt;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel VisualizarBtn;
    private javax.swing.JLabel VisualizarTxt;
    private javax.swing.JLabel buscarPng;
    private javax.swing.JTextField clienteTxt;
    private javax.swing.JLabel generarPng;
    private javax.swing.JLabel imprimirPng;
    private javax.swing.JLabel imprimirPng1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JLabel visualizarPng;
    // End of variables declaration//GEN-END:variables
}
