/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import conexion.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leider
 */
public class Historial extends javax.swing.JPanel {
    Color naranja=new Color(0,15,29);
    Color naranjado=new Color(255,180,80);
    
    Conexion con= new Conexion();
    Connection cn;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel modelo;
    
    public Historial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        MostrarBtn = new javax.swing.JPanel();
        MostrarTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 15, 29));

        jPanel1.setBackground(new java.awt.Color(0, 15, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane1.setBorder(null);

        tblHistorial.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de factura", "Id del Cliente", "Fecha de facturación", "Valor", "Estado", "Fecha de pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHistorial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );

        MostrarBtn.setBackground(new java.awt.Color(0, 15, 29));
        MostrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarBtnMouseExited(evt);
            }
        });

        MostrarTxt.setBackground(new java.awt.Color(0, 51, 102));
        MostrarTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        MostrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        MostrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MostrarTxt.setText("Mostrar");

        javax.swing.GroupLayout MostrarBtnLayout = new javax.swing.GroupLayout(MostrarBtn);
        MostrarBtn.setLayout(MostrarBtnLayout);
        MostrarBtnLayout.setHorizontalGroup(
            MostrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostrarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MostrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );
        MostrarBtnLayout.setVerticalGroup(
            MostrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MostrarTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(MostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarBtnMouseClicked
        mostrarPagos();
    }//GEN-LAST:event_MostrarBtnMouseClicked

    private void MostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarBtnMouseEntered
        MostrarBtn.setBackground(naranjado);
        MostrarTxt.setForeground(Color.black);
    }//GEN-LAST:event_MostrarBtnMouseEntered

    private void MostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarBtnMouseExited
        MostrarBtn.setBackground(naranja);
        MostrarTxt.setForeground(Color.white);
    }//GEN-LAST:event_MostrarBtnMouseExited
    
    private void inv(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"01","02","03","04","05","06","07","08"
                ,"09" ,"10","11","12"};
        String fecha=(year+"-"+meses[month - 1]+"-"+dia);
        
        Date fecha_act;
        int diaa = 31;
        int mess = 0;
        int año =2022;
        
        if(year==año  ){
           // if(nom.equals("")||ced.equals("")||dir.equals("")||fec.equals("")||tel.equals(""))
        }else{
            
        }
        
    }
   
    private void mostrarPagos(){            
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"01","02","03","04","05","06","07","08"
                ,"09" ,"10","11","12"};
        String fecha=(year+"-"+meses[month - 1]+"-"+dia);        
        String sql = "select * from factura where fecha_pag='"+fecha+"'";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]factura=new Object[6];
            modelo=(DefaultTableModel)tblHistorial.getModel();
            while(rs.next()){
                factura[0]=rs.getInt("num_factura");
                factura[1]=rs.getInt("id_cliente");
                factura[2]=rs.getDate("fecha_fact");
                factura[3]=rs.getInt("valor");
                factura[4]=rs.getString("estado");
                factura[5]=rs.getDate("fecha_pag");
                modelo.addRow(factura);
            }
            tblHistorial.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MostrarBtn;
    private javax.swing.JLabel MostrarTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
