/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import conexion.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leider
 */
public class Informe extends javax.swing.JPanel {
    
    Color naranja=new Color(0,15,29);
    Color naranjado=new Color(255,180,80);
    
    Conexion con= new Conexion();
    Connection cn;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel modelo;
    int id;
    
    public Informe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        alDiaBtn = new javax.swing.JPanel();
        alDiaTxt = new javax.swing.JLabel();
        pendientesBtn = new javax.swing.JPanel();
        pendientesTxt = new javax.swing.JLabel();
        reporteBtn = new javax.swing.JPanel();
        reporteTxt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        content = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInforme = new javax.swing.JTable();
        Titulo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        Contenido.setBackground(new java.awt.Color(0, 15, 29));
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 15, 29));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 2, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alDiaBtn.setBackground(new java.awt.Color(0, 15, 29));
        alDiaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alDiaBtn.setPreferredSize(new java.awt.Dimension(242, 56));
        alDiaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alDiaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alDiaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alDiaBtnMouseExited(evt);
            }
        });

        alDiaTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        alDiaTxt.setForeground(new java.awt.Color(255, 255, 255));
        alDiaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alDiaTxt.setText("Mostrar al dia");

        javax.swing.GroupLayout alDiaBtnLayout = new javax.swing.GroupLayout(alDiaBtn);
        alDiaBtn.setLayout(alDiaBtnLayout);
        alDiaBtnLayout.setHorizontalGroup(
            alDiaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alDiaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        alDiaBtnLayout.setVerticalGroup(
            alDiaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alDiaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alDiaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(alDiaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 242, 50));

        pendientesBtn.setBackground(new java.awt.Color(0, 15, 29));
        pendientesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendientesBtn.setPreferredSize(new java.awt.Dimension(242, 56));
        pendientesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendientesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pendientesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pendientesBtnMouseExited(evt);
            }
        });

        pendientesTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        pendientesTxt.setForeground(new java.awt.Color(255, 255, 255));
        pendientesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendientesTxt.setText("Mostrar pendientes");

        javax.swing.GroupLayout pendientesBtnLayout = new javax.swing.GroupLayout(pendientesBtn);
        pendientesBtn.setLayout(pendientesBtnLayout);
        pendientesBtnLayout.setHorizontalGroup(
            pendientesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendientesTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        pendientesBtnLayout.setVerticalGroup(
            pendientesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendientesBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendientesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(pendientesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 242, 50));

        reporteBtn.setBackground(new java.awt.Color(0, 15, 29));
        reporteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reporteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reporteBtnMouseExited(evt);
            }
        });

        reporteTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reporteTxt.setForeground(new java.awt.Color(255, 255, 255));
        reporteTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reporteTxt.setText("Reporte");

        javax.swing.GroupLayout reporteBtnLayout = new javax.swing.GroupLayout(reporteBtn);
        reporteBtn.setLayout(reporteBtnLayout);
        reporteBtnLayout.setHorizontalGroup(
            reporteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reporteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        reporteBtnLayout.setVerticalGroup(
            reporteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reporteTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel5.add(reporteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 242, 50));

        Contenido.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 300, 250));

        jPanel6.setBackground(new java.awt.Color(0, 15, 29));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 2, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de factura", "Id del cliente", "Fecha de factura", "Valor", "Estado", "Fecha de pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetalles);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        Contenido.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 310));

        content.setBackground(new java.awt.Color(0, 51, 102));

        tblInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id informe", "Recaudo del Mes", "Saldos en mora", "fecha de informe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblInforme);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Contenido.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 378, 190));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 15, 29));
        jLabel10.setText("Informes");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reporteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseExited
        reporteBtn.setBackground(naranja);
        reporteTxt.setForeground(Color.white);
    }//GEN-LAST:event_reporteBtnMouseExited

    private void reporteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseEntered
        reporteBtn.setBackground(naranjado);
        reporteTxt.setForeground(Color.black);
    }//GEN-LAST:event_reporteBtnMouseEntered

    private void pendientesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendientesBtnMouseExited
        pendientesBtn.setBackground(naranja);
        pendientesTxt.setForeground(Color.white);
    }//GEN-LAST:event_pendientesBtnMouseExited

    private void pendientesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendientesBtnMouseEntered
        pendientesBtn.setBackground(naranjado);
        pendientesTxt.setForeground(Color.black);
    }//GEN-LAST:event_pendientesBtnMouseEntered

    private void alDiaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alDiaBtnMouseExited
        alDiaBtn.setBackground(naranja);
        alDiaTxt.setForeground(Color.white);
    }//GEN-LAST:event_alDiaBtnMouseExited

    private void alDiaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alDiaBtnMouseEntered
        alDiaBtn.setBackground(naranjado);
        alDiaTxt.setForeground(Color.black);
    }//GEN-LAST:event_alDiaBtnMouseEntered

    private void alDiaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alDiaBtnMouseClicked

    }//GEN-LAST:event_alDiaBtnMouseClicked

    private void reporteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseClicked
        /*Infor inf = new Infor();
        inf.setSize(378, 290);
        inf.setLocation(0,0);
        
        content.removeAll();
        content.add(inf, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();*/
        inform();
    }//GEN-LAST:event_reporteBtnMouseClicked

    private void pendientesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendientesBtnMouseClicked
        operar();
    }//GEN-LAST:event_pendientesBtnMouseClicked

    private void operar(){
         
        String sql = "select * from moras;";

        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            rs = st.executeQuery(sql);
            Object[]mora=new Object[2];
            modelo=(DefaultTableModel)tblInforme.getModel();
            while(rs.next()){
                mora[0]=rs.getInt("valor_total");
                mora[1]=rs.getInt("id_cliente");
                modelo.addRow(mora);
            }
            tblInforme.setModel(modelo);
            JOptionPane.showMessageDialog(null,"consulta exitosa");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"pailassss");
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }
    
    private void inform(){   
        String sql = " insert into informe (recaudoMes, saldosMora) values\n" +
                     " ((select (count(valor)*20000)-(select sum(valor) from factura WHERE estado='pendiente' \n" +
                     "and fecha_fact='2022-01-30')from factura WHERE fecha_fact='2022-01-30'),\n" +
                     " (select sum(valor) from factura WHERE estado='pendiente' and fecha_fact='2022-01-30'));";
        String sql2 ="select * from informe";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            st.executeUpdate(sql);
            rs = st.executeQuery(sql2);
            Object[]factura=new Object[4];
            modelo=(DefaultTableModel)tblInforme.getModel();
            while(rs.next()){
                factura[0]=rs.getInt("id_informe");
                factura[1]=rs.getInt("recaudoMes");
                factura[2]=rs.getInt("saldosMora");
                factura[3]=rs.getDate("fech_inf");
                modelo.addRow(factura);
            }
            tblInforme.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel alDiaBtn;
    private javax.swing.JLabel alDiaTxt;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pendientesBtn;
    private javax.swing.JLabel pendientesTxt;
    private javax.swing.JPanel reporteBtn;
    private javax.swing.JLabel reporteTxt;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTable tblInforme;
    // End of variables declaration//GEN-END:variables
}
