package app;

import conexion.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pagos extends javax.swing.JPanel {

    Color naranja=new Color(0,15,29);
    Color naranjado=new Color(255,180,80);
    
    Conexion con= new Conexion();
    Connection cn;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel modelo;
    
    public Pagos() {
        initComponents();
        pagarPng.setIcon(new javax.swing.ImageIcon("./img/moneyb.png"));
        historialPng.setIcon(new javax.swing.ImageIcon("./img/historialb.png"));
        imprimirPng.setIcon(new javax.swing.ImageIcon("./img/printb.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        datosDePago = new javax.swing.JPanel();
        idDelClienteBtn = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numFacTxt = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        valorText = new javax.swing.JTextField();
        pagarBtn = new javax.swing.JPanel();
        pagarTxt = new javax.swing.JLabel();
        pagarPng = new javax.swing.JLabel();
        historialBtn = new javax.swing.JPanel();
        historialTxt = new javax.swing.JLabel();
        historialPng = new javax.swing.JLabel();
        imprimirBtn = new javax.swing.JPanel();
        imprimirTxt = new javax.swing.JLabel();
        imprimirPng = new javax.swing.JLabel();
        hisContent = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 660));

        Contenido.setBackground(new java.awt.Color(0, 15, 29));

        datosDePago.setBackground(new java.awt.Color(0, 15, 29));
        datosDePago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        idDelClienteBtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idDelClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        idDelClienteBtn.setText("Id Del Cliente:");

        idTxt.setBackground(new java.awt.Color(0, 15, 29));
        idTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idTxt.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero de Factura:");

        numFacTxt.setBackground(new java.awt.Color(0, 15, 29));
        numFacTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        numFacTxt.setForeground(new java.awt.Color(255, 255, 255));

        valor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        valor.setForeground(new java.awt.Color(255, 255, 255));
        valor.setText("Valor:");

        valorText.setBackground(new java.awt.Color(0, 15, 29));
        valorText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        valorText.setForeground(new java.awt.Color(255, 255, 255));

        pagarBtn.setBackground(new java.awt.Color(0, 15, 29));
        pagarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pagarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pagarBtnMouseExited(evt);
            }
        });

        pagarTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        pagarTxt.setForeground(new java.awt.Color(255, 255, 255));
        pagarTxt.setText("Pagar");

        pagarPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pagarBtnLayout = new javax.swing.GroupLayout(pagarBtn);
        pagarBtn.setLayout(pagarBtnLayout);
        pagarBtnLayout.setHorizontalGroup(
            pagarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pagarPng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagarTxt)
                .addGap(34, 34, 34))
        );
        pagarBtnLayout.setVerticalGroup(
            pagarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pagarPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pagarTxt, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        historialBtn.setBackground(new java.awt.Color(0, 15, 29));
        historialBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historialBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historialBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historialBtnMouseExited(evt);
            }
        });

        historialTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        historialTxt.setForeground(new java.awt.Color(255, 255, 255));
        historialTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historialTxt.setText("Historial");

        historialPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout historialBtnLayout = new javax.swing.GroupLayout(historialBtn);
        historialBtn.setLayout(historialBtnLayout);
        historialBtnLayout.setHorizontalGroup(
            historialBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historialBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(historialPng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historialTxt)
                .addGap(15, 15, 15))
        );
        historialBtnLayout.setVerticalGroup(
            historialBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historialBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(historialBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historialPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historialTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        imprimirBtn.setBackground(new java.awt.Color(0, 15, 29));
        imprimirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imprimirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imprimirBtnMouseExited(evt);
            }
        });

        imprimirTxt.setBackground(new java.awt.Color(255, 255, 255));
        imprimirTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        imprimirTxt.setForeground(new java.awt.Color(255, 255, 255));
        imprimirTxt.setText("Imprimir");

        imprimirPng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout imprimirBtnLayout = new javax.swing.GroupLayout(imprimirBtn);
        imprimirBtn.setLayout(imprimirBtnLayout);
        imprimirBtnLayout.setHorizontalGroup(
            imprimirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imprimirPng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimirTxt)
                .addGap(14, 14, 14))
        );
        imprimirBtnLayout.setVerticalGroup(
            imprimirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imprimirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imprimirPng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(imprimirBtnLayout.createSequentialGroup()
                        .addComponent(imprimirTxt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout datosDePagoLayout = new javax.swing.GroupLayout(datosDePago);
        datosDePago.setLayout(datosDePagoLayout);
        datosDePagoLayout.setHorizontalGroup(
            datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosDePagoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDePagoLayout.createSequentialGroup()
                        .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDePagoLayout.createSequentialGroup()
                                    .addComponent(idDelClienteBtn)
                                    .addGap(55, 55, 55))
                                .addGroup(datosDePagoLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(15, 15, 15)))
                            .addGroup(datosDePagoLayout.createSequentialGroup()
                                .addComponent(valor)
                                .addGap(100, 100, 100)))
                        .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numFacTxt)
                            .addComponent(idTxt)
                            .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDePagoLayout.createSequentialGroup()
                        .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imprimirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pagarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(historialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        datosDePagoLayout.setVerticalGroup(
            datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosDePagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDelClienteBtn)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numFacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosDePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor)
                    .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(imprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(historialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hisContent.setBackground(new java.awt.Color(0, 15, 29));

        javax.swing.GroupLayout hisContentLayout = new javax.swing.GroupLayout(hisContent);
        hisContent.setLayout(hisContentLayout);
        hisContentLayout.setHorizontalGroup(
            hisContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        hisContentLayout.setVerticalGroup(
            hisContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hisContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datosDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hisContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        Titulo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 15, 29));
        jLabel10.setText("Pagos");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pagarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarBtnMouseEntered
        pagarBtn.setBackground(naranjado);
        pagarTxt.setForeground(Color.black);
        pagarPng.setIcon(new javax.swing.ImageIcon("./img/money.png"));
    }//GEN-LAST:event_pagarBtnMouseEntered

    private void pagarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarBtnMouseExited
        pagarBtn.setBackground(naranja);
        pagarTxt.setForeground(Color.white);
        pagarPng.setIcon(new javax.swing.ImageIcon("./img/moneyb.png"));
    }//GEN-LAST:event_pagarBtnMouseExited

    private void historialBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBtnMouseEntered
        historialBtn.setBackground(naranjado);
        historialTxt.setForeground(Color.black);
        historialPng.setIcon(new javax.swing.ImageIcon("./img/historial.png"));
    }//GEN-LAST:event_historialBtnMouseEntered

    private void historialBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBtnMouseExited
        historialBtn.setBackground(naranja);
        historialTxt.setForeground(Color.white);
        historialPng.setIcon(new javax.swing.ImageIcon("./img/historialb.png"));
    }//GEN-LAST:event_historialBtnMouseExited

    private void imprimirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirBtnMouseEntered
        imprimirBtn.setBackground(naranjado);
        imprimirTxt.setForeground(Color.black);
        imprimirPng.setIcon(new javax.swing.ImageIcon("./img/print.png"));
    }//GEN-LAST:event_imprimirBtnMouseEntered

    private void imprimirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirBtnMouseExited
        imprimirBtn.setBackground(naranja);
        imprimirTxt.setForeground(Color.white);
        imprimirPng.setIcon(new javax.swing.ImageIcon("./img/printb.png"));
    }//GEN-LAST:event_imprimirBtnMouseExited

    private void historialBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBtnMouseClicked
        Historial hi = new Historial();
        hi.setSize(573, 330);
        hi.setLocation(0,0);
        
        hisContent.removeAll();
        hisContent.add(hi, BorderLayout.CENTER);
        hisContent.revalidate();
        hisContent.repaint();
    }//GEN-LAST:event_historialBtnMouseClicked

    private void pagarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarBtnMouseClicked
        pagar();
    }//GEN-LAST:event_pagarBtnMouseClicked

    private void pagar(){
        
        int valo= Integer.parseInt(valorText.getText());
        int id= Integer.parseInt(idTxt.getText());        
        int numFac= Integer.parseInt(numFacTxt.getText());        

        String sql = "update factura set valor = valor-'"+valo+"', estado = if( valor<=0, 'al dia','pendiente'), valor=if(valor<=0,'0',valor) WHERE (num_factura = '"+numFac+"' and id_cliente = '"+id+"')";
       
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Pago procesado");
            System.out.println();
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel datosDePago;
    private javax.swing.JPanel hisContent;
    private javax.swing.JPanel historialBtn;
    private javax.swing.JLabel historialPng;
    private javax.swing.JLabel historialTxt;
    private javax.swing.JLabel idDelClienteBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JPanel imprimirBtn;
    private javax.swing.JLabel imprimirPng;
    private javax.swing.JLabel imprimirTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField numFacTxt;
    private javax.swing.JPanel pagarBtn;
    private javax.swing.JLabel pagarPng;
    private javax.swing.JLabel pagarTxt;
    private javax.swing.JLabel valor;
    private javax.swing.JTextField valorText;
    // End of variables declaration//GEN-END:variables
}
